apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: cobrakai
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
      containers:
        - name: grafana
          image: grafana/grafana:11.1.4
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/prometheus-datasource.yaml
              subPath: prometheus-datasource.yaml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/timeline-dashboard-provider.yaml
              subPath: timeline-dashboard-provider.yaml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/timeline-dashboard.json
              subPath: timeline-dashboard.json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: cobrakai
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
